CREATE TABLE plan_setting
(
  id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  name VARCHAR(32) DEFAULT '' NOT NULL,
  name_pinyin TEXT DEFAULT '' NOT NULL,
  plan_type BIT DEFAULT 0 NOT NULL,
  is_adjust_showcase BIT DEFAULT 0 NOT NULL,
  exclude_item_iids TEXT DEFAULT '' NOT NULL,
  include_cids TEXT DEFAULT '' NOT NULL,
  adjust_intervals TEXT DEFAULT '' NOT NULL,
  adjust_intervals_type BIT DEFAULT 0 NOT NULL,
  status INT DEFAULT 0 NOT NULL,
  last_adjust_item_num INT DEFAULT 0 NOT NULL,
  last_adjust_time TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
  add_time TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
  upd_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE plan
(
  id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  plan_setting_id BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  user_id BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  item_iid BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  item_name VARCHAR(32) DEFAULT '' NOT NULL,
  item_pic_url TEXT DEFAULT '' NOT NULL,
  status INT UNSIGNED DEFAULT 0 NOT NULL,
  plan_listing_time TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
  listing_time TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
  add_time TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
  upd_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
